Config = {}

Config.Locations = {
    ["main"] = {
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },
    ["thermite"] = {
        x = 363.47,
        y = 74.3,
        z = 97.97,
        isDone = false,
        isBusy = false,
    },
    ["takeables"] = {
        [1] = {
            x = 374.87,
            y = 104.87,
            z = 103.13,
            isDone = false,
            isBusy = false,
            reward =  {name = "iphone", amount = 6},
        },
        [2] = {
            x = 374.137,
            y = 102.61,
            z = 103.13,
            isDone = false,
            isBusy = false,
            reward =  {name = "laptop", amount = 3},
        },
        [3] = {
            x = 373.34,
            y = 100.67,
            z =  103.13,
            isDone = false,
            isBusy = false,
            reward =  {name = "samsungphone", amount = 8},
        },
        [4] = {
            x = 368.92,
            y = 106.62,
            z = 103.13,
            isDone = false,
            isBusy = false,
            reward =  {name = "iphone", amount = 4},
        },
        [5] = {
            x = 367.49,
            y = 103.01,
            z = 103.13,
            isDone = false,
            isBusy = false,
            reward =  {name = "samsungphone", amount = 4},
        },
        [6] = {
            x = 369.86,
            y = 104.8,
            z = 103.13,
            isDone = false,
            isBusy = false,
            reward =  {name = "laptop", amount = 3},
        },
        [7] = {
            x = 370.87,
            y = 107.42,
            z = 103.13,
            isDone = false,
            isBusy = false,
            reward =  {name = "tablet", amount = 4},
        },
        [8] = {
            x = 369.47,
            y = 103.66,
            z = 103.13,
            isDone = false,
            isBusy = false,
            reward =  {name = "laptop", amount = 3},
        },
        [9] = {
            x = 368.58, 
            y = 101.11, 
            z = 103.13,
            isDone = false,
            isBusy = false,
            reward =  {name = "iphone", amount = 6},
        },
    },
    -- ["safe"] = {
    --     x = -625.37, 
    --     y = -283.74, 
    --     z = 35.57,
    --     isDone = false,
    --     isBusy = false,
    -- }
}

Config.MaleNoHandshoes = {
    [0] = true,
    [1] = true,
    [2] = true,
    [3] = true,
    [4] = true,
    [5] = true,
    [6] = true,
    [7] = true,
    [8] = true,
    [9] = true,
    [10] = true,
    [11] = true,
    [12] = true,
    [13] = true,
    [14] = true,
    [15] = true,
    [18] = true,
    [26] = true,
    [52] = true,
    [53] = true,
    [54] = true,
    [55] = true,
    [56] = true,
    [57] = true,
    [58] = true,
    [59] = true,
    [60] = true,
    [61] = true,
    [62] = true,
    [112] = true,
    [113] = true,
    [114] = true,
    [118] = true,
    [125] = true,
    [132] = true,
}

Config.FemaleNoHandshoes = {
    [0] = true,
    [1] = true,
    [2] = true,
    [3] = true,
    [4] = true,
    [5] = true,
    [6] = true,
    [7] = true,
    [8] = true,
    [9] = true,
    [10] = true,
    [11] = true,
    [12] = true,
    [13] = true,
    [14] = true,
    [15] = true,
    [19] = true,
    [59] = true,
    [60] = true,
    [61] = true,
    [62] = true,
    [63] = true,
    [64] = true,
    [65] = true,
    [66] = true,
    [67] = true,
    [68] = true,
    [69] = true,
    [70] = true,
    [71] = true,
    [129] = true,
    [130] = true,
    [131] = true,
    [135] = true,
    [142] = true,
    [149] = true,
    [153] = true,
    [157] = true,
    [161] = true,
    [165] = true,
}